// Generated by Wrangler on Sat Aug 10 2024 00:48:54 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	ANALYTICS_KV: KVNamespace;
	IS_DEVELOPMENT_MODE: string;
	ANALYTICS_DB: D1Database;
}
